# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PycharmProjects\QT_Disigner\Vista_QT\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSettings
from PyQt5.QtWidgets import QMessageBox


class Ui_Authorization(object):
    def setupUi(self, Authorization):
        Authorization.setObjectName("Authorization")
        Authorization.resize(538, 405)
        self.centralwidget = QtWidgets.QWidget(Authorization)
        self.centralwidget.setObjectName("centralwidget")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget, placeholderText="Имя пользователя")
        self.lineEdit.setGeometry(QtCore.QRect(90, 70, 361, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget, placeholderText="Пароль")
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 110, 361, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 190, 161, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("background-color: green")
        self.pushButton.clicked.connect(self.auth_btn)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 190, 161, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.reg_btn)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 190, 161, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet("background-color: red")

        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(110, 250, 131, 31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.stateChanged.connect(self.check)

        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(110, 280, 131, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.stateChanged.connect(self.doCheck)



        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 350, 141, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.rep_pass)

        Authorization.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Authorization)
        self.statusbar.setObjectName("statusbar")
        Authorization.setStatusBar(self.statusbar)

        self.retranslateUi(Authorization)
        QtCore.QMetaObject.connectSlotsByName(Authorization)

        self.pushButton.setText("Войти")
        self.pushButton_2.setText("Регистрация")
        self.pushButton_3.setText("Отмена")
        self.checkBox.setText("Запомнить меня")
        self.checkBox_2.setText("Показать пароль")
        self.pushButton_4.setText("Забыли пароль")
        self.get_checkbox()


    def retranslateUi(self, Authorization):
        _translate = QtCore.QCoreApplication.translate
        Authorization.setWindowTitle(_translate("Authorization", "Test_Vista"))
        '''
        self.pushButton.setText(_translate("Authorization", "Войти"))
        self.pushButton_2.setText(_translate("Authorization", "Регистрация"))
        self.pushButton_3.setText(_translate("Authorization", "Отмена"))
        #self.checkBox.setText(_translate("MainWindow", "Запомнить меня"))
        self.checkBox_2.setText(_translate("Authorization", "Показать пароль"))
        self.pushButton_4.setText(_translate("Authorization", "Забыли пароль"))
        '''
    def get_checkbox(self):
        import main
        import sql_req
        req = sql_req.check_last_user(main.conn)

        if len(req) != 0:
            self.lineEdit.setText(req[0]['login'])
            self.lineEdit_2.setText(req[0]['password'])
            self.checkBox.setChecked(True)


    def rep_pass(self):
        self.setupUi_rep_pass(self)

    def auth_btn(self):
        import main
        import sql_req
        login = self.lineEdit.text()
        password = self.lineEdit_2.text()
        if sql_req.auth(main.conn, login, password):
            if self.checkBox.isChecked():
                m = sql_req.check_last_user(main.conn)
                if len(m) == 0:
                    sql_req.add_last_user(main.conn, login, password)
            else:
                sql_req.del_last_user(main.conn)

            self.setupUi_phone_book(self)
        else:
            msg = QMessageBox()
            msg.setWindowTitle(" ")
            msg.setText("Пользователь с такими данными не найден.")
            msg.setIcon(QMessageBox.Warning)
            msg.exec_()


    def reg_btn(self):
        self.setupUi_reg(self)

    def doCheck(self):
        if self.checkBox_2.isChecked():
            self.lineEdit_2.setEchoMode(False)
        else:
            self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)

    def check(self):
        if self.checkBox.isChecked():
            pass
        else:
            import main
            import sql_req
            sql_req.del_last_user(main.conn)

