# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PycharmProjects\QT_Disigner\Vista_QT\design_rep_pass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Window_rep_pass(object):
    def setupUi_rep_pass(self, Window_rep_pass):
        Window_rep_pass.setObjectName("Window_rep_pass")
        Window_rep_pass.resize(538, 405)
        self.centralwidget = QtWidgets.QWidget(Window_rep_pass)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget, placeholderText="Адрес электронной почты")
        self.lineEdit.setGeometry(QtCore.QRect(90, 140, 361, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 200, 161, 31))
        self.pushButton_5.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 200, 161, 31))
        self.pushButton_6.setObjectName("pushButton_2")
        self.pushButton_6.setStyleSheet("background-color: red")
        Window_rep_pass.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Window_rep_pass)
        self.statusbar.setObjectName("statusbar")
        Window_rep_pass.setStatusBar(self.statusbar)

        self.retranslateUi(Window_rep_pass)
        QtCore.QMetaObject.connectSlotsByName(Window_rep_pass)
        self.pushButton_5.setText("Сменить пароль")
        self.pushButton_6.setText("Отмена")
        self.pushButton_6.clicked.connect(self.btn_cancel)
    def retranslateUi(self, Window_rep_pass):
        _translate = QtCore.QCoreApplication.translate
        Window_rep_pass.setWindowTitle(_translate("Window_rep_pass", "MainWindow"))

    def btn_cancel(self):
        self.setupUi(self)