# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PycharmProjects\QT_Disigner\Vista_QT\book_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Redact(object):
    def setupUi_redact(self, Redact):
        Redact.setObjectName("Redact")
        Redact.resize(536, 405)
        self.centralwidget = QtWidgets.QWidget(Redact)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 20, 341, 361))
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setHorizontalHeaderLabels(['Имя', 'Телефон', 'Дата рождения'])
        self.tableWidget.clicked.connect(self.clicked_table)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 51, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.press_btn)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 60, 51, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.press_btn)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 80, 51, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.press_btn)

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 100, 51, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.press_btn)

        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 120, 51, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.press_btn)

        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 140, 51, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.press_btn)

        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 160, 51, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.press_btn)

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 180, 51, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.press_btn)

        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 200, 51, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.press_btn)

        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 220, 51, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.press_btn)

        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 240, 51, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.press_btn)

        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 260, 51, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.press_btn)

        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 280, 51, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.press_btn)

        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(420, 300, 101, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(self.press_btn)

        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(420, 340, 101, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(self.press_btn)

        Redact.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Redact)
        self.statusbar.setObjectName("statusbar")
        Redact.setStatusBar(self.statusbar)

        self.retranslateUi(Redact)
        QtCore.QMetaObject.connectSlotsByName(Redact)

        self.pushButton.setText("АБ")
        self.pushButton_2.setText("ВГ")
        self.pushButton_3.setText("ДЕ")
        self.pushButton_4.setText("ЖЗИЙ")
        self.pushButton_5.setText("КЛ")
        self.pushButton_6.setText("МН")
        self.pushButton_7.setText("ОП")
        self.pushButton_8.setText("РС")
        self.pushButton_9.setText("ТУ")
        self.pushButton_10.setText("ФХ")
        self.pushButton_11.setText("ЦЧШЩ")
        self.pushButton_12.setText("ЪЫЬЭ")
        self.pushButton_13.setText("ЮЯ")
        self.pushButton_14.setText("Сохранить")
        self.pushButton_15.setText("Отмена")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def press_btn(self):
        import sql_req
        import main
        sender = self.sender()

        if sender.objectName() == 'pushButton':
            self.tableWidget.clear()
            self.pushButton.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton.setEnabled(True)

        if sender.objectName() == 'pushButton_2':
            self.tableWidget.clear()
            self.pushButton_2.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_2.setEnabled(True)

        if sender.objectName() == 'pushButton_3':
            self.tableWidget.clear()
            self.pushButton_3.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_3.setEnabled(True)

        if sender.objectName() == 'pushButton_4':
            self.tableWidget.clear()
            self.pushButton_4.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_4.setEnabled(True)

        if sender.objectName() == 'pushButton_5':
            self.tableWidget.clear()
            self.pushButton_5.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_5.setEnabled(True)

        if sender.objectName() == 'pushButton_6':
            self.tableWidget.clear()
            self.pushButton_6.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_6.setEnabled(True)

        if sender.objectName() == 'pushButton_7':
            self.tableWidget.clear()
            self.pushButton_7.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_7.setEnabled(True)

        if sender.objectName() == 'pushButton_8':
            self.tableWidget.clear()
            self.pushButton_8.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_8.setEnabled(True)

        if sender.objectName() == 'pushButton_9':
            self.tableWidget.clear()
            self.pushButton_9.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_9.setEnabled(True)

        if sender.objectName() == 'pushButton_10':
            self.tableWidget.clear()
            self.pushButton_10.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_10.setEnabled(True)

        if sender.objectName() == 'pushButton_11':
            self.tableWidget.clear()
            self.pushButton_11.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_11.setEnabled(True)

        if sender.objectName() == 'pushButton_12':
            self.tableWidget.clear()
            self.pushButton_12.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_12.setEnabled(True)

        if sender.objectName() == 'pushButton_13':
            self.tableWidget.clear()
            self.pushButton_13.setEnabled(False)
            req = sql_req.request_Abc(main.conn, sender.text())
            self.fill_table(req)
        else:
            self.pushButton_13.setEnabled(True)

        if sender.objectName() == 'pushButton_14':
            pass

        if sender.objectName() == 'pushButton_15':
            pass

    def clicked_table(self):
        rows = sorted(set(index.row() for index in
                      self.tableWidget.selectedIndexes()))
        for row in rows:
            print('Row %d is selected' % row)
        print(row)
        self.tableWidget.selectRow(row)
