# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PycharmProjects\QT_Disigner\Vista_QT\registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox



class Registration(object):
    def setupUi_reg(self, Registration):
        Registration.setObjectName("Reg")
        Registration.resize(538, 405)
        self.centralwidget = QtWidgets.QWidget(Registration)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget,placeholderText="Имя пользователя")
        self.lineEdit.setGeometry(QtCore.QRect(80, 70, 361, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget,placeholderText="Пароль")
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 130, 361, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget,placeholderText="Повторите пароль")
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 190, 361, 31))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(280, 310, 161, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setStyleSheet("background-color: red")
        self.pushButton_8.clicked.connect(self.btn_cancel)

        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 310, 161, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.btn_reg)

        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(80, 250, 361, 31))
        self.dateEdit_2.setObjectName("dateEdit_2")
        Registration.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Registration)
        self.statusbar.setObjectName("statusbar")
        Registration.setStatusBar(self.statusbar)

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

        self.pushButton_8.setText("Отмена")
        self.pushButton_7.setText("Ok")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Reg", "MainWindow"))

    def btn_cancel(self):
        self.setupUi(self)

    def btn_reg(self):
        import main
        import sql_req
        login = self.lineEdit.text()
        password = self.lineEdit_2.text()
        rep_password = self.lineEdit_3.text()
        date = self.dateEdit_2.date()
        if password != rep_password:
            msg = QMessageBox()
            msg.setWindowTitle(" ")
            msg.setText("Пароли не совпадают.")
            msg.setIcon(QMessageBox.Warning)
            msg.exec_()
        elif sql_req.check_user(main.conn, login):
            print(sql_req.check_user(main.conn, login))
            msg = QMessageBox()
            msg.setWindowTitle(" ")
            msg.setText("Такой пользователь уже есть.")
            msg.setIcon(QMessageBox.Warning)
            msg.exec_()
        else:
            sql_req.add_user(main.conn, login, password, date)
            self.setupUi(self)


